server:
  port: 8082

spring:
  application:
    name: vehicle-service
  datasource:
    url: jdbc:postgresql://localhost:5432/autobidder
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

jpa:
   hibernate:
      ddl-auto: update
   show-sql: true
   database-platform: org.hibernate.dialect.PostgreSQLDialect
   

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true